---
# handlers file for bacula_file_daemon
- name: Restart the Bacula Director
  ansible.builtin.service:
    name: "{{ bacula_file_daemon_service_name }}"
    state: "{{ bacula_file_daemon_service_restarted }}"
  listen:
    - "restart bacula daemon"
  tags:
    - bacula_daemon_handler
    - bacula_file_daemon_handler
    - handler
    - bacula_daemon_restart
    - bacula_file_daemon_restart
    - restart
  when:
    - "bacula_file_daemon_service_restarted is not none"
