---
galaxy_info:
  author: dudefellah
  role_name: bacula
  description: Install and configure Bacula Director

  license: GPL-2.0-or-later

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - backup
    - bacula
    - director
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
