---
# Installing a Bacula director using the `bacula_daemon` role instead of the
# `bacula_director` role. Note that this won't handle the Catalog
# configuration on Red Hat systems, and it will generate a catalog database
# with a random password on Debian systems.
- hosts: bacula_directors
  tasks:
    - block:
        - name: Configure the Bacula Directors
          include_role:
            name: dudefellah.bacula.bacula_daemon
          vars:
            bacula_daemon_packages: "{{ bacula_daemon_director_packages | default(['bacula-director']) }}"
            bacula_daemon_owner: "{{ bacula_daemon_director_owner | default('bacula') }}"
            bacula_daemon_group: "{{ bacula_daemon_director_group | default('bacula') }}"
            bacula_daemon_default_dir_mode: "{{ bacula_daemon_director_default_dir_node | default('0750') }}"
            bacula_daemon_default_file_mode: "{{ bacula_daemon_director_default_file_mode | default('0640') }}"
            bacula_daemon_default_template_validate: "{{ bacula_daemon_director_default_template_validate | default('bacula-dir -t %s') }}"
            bacula_daemon_no_log: "{{ bacula_daemon_director_no_log | default(true) }}"
            bacula_daemon_init_scripts: "{{ bacula_daemon_director_init_scripts | default([]) }}"
            bacula_daemon_base_config_file: "{{ bacula_daemon_director_base_config_file | default('bacula-dir.conf') }}"
            bacula_daemon_base_config_mode: "{{ bacula_daemon_director_base_config_mode | default('0640') }}"
            bacula_daemon_base_config_owner: "{{ bacula_daemon_director_base_config_owner | default('bacula') }}"
            bacula_daemon_base_config_group: "{{ bacula_daemon_director_base_config_group | default('bacula') }}"
            bacula_daemon_config_root: "{{ bacula_daemon_director_base_config_root | default({'path': '/etc/bacula', 'owner': 'bacula', 'group': 'bacula', 'mode': '0640'}) }}"
            bacula_daemon_resources: "{{ bacula_daemon_director_resources | default([]) }}"
      become: true
