---
# handlers file for bacula_director
- name: Restart the Bacula Director
  ansible.builtin.service:
    name: "{{ bacula_director_service_name }}"
    state: "{{ bacula_director_service_restarted }}"
  listen:
    - "restart bacula daemon"
  tags:
    - bacula_daemon_handler
    - bacula_director_handler
    - handler
    - bacula_daemon_restart
    - bacula_director_restart
    - restart
  when:
    - "bacula_director_service_restarted is not none"
